language: ruby

rvm:
 - 2.1.0

before_install:
 - curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
 - sudo apt-get install -qq nodejs

before_script:
 - npm install -g ember-cli
 - (cd rails && bundle install)
 - (cd ember && npm install)

script:
 - (cd rails && bundle exec rake)
 - (cd ember && ember test)
