language: node_js

node_js:
 - "0.12"

install:
 - npm install -g ember-cli bower
 - (cd rails && bundle install)
 - (cd ember && npm install)

script:
 - (cd rails && bundle exec rake)
 - (cd ember && npm test)
