language: ruby
rvm:
 - 2.1.0

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq npm

before_script:
 - npm install -g ember-cli

script:
 - rails/bundle exec rake
 - ember/ember test
