language: node_js

node_js:
 - "0.12"

cache:
 directories:
 - ember/node_modules
 - ember/bower_components
 - rails/vendor/bundle

before_install:
 - rvm install 2.2.0

install:
 - (cd ember && npm install)
 - (cd ember && bower install)
 - (cd rails && bundle install --path vendor/bundle)

script:
 - (cd ember && npm test)
 - (cd rails && bundle exec rake)
